
from typing import Protocol


class Mailbox(Protocol):
    def send(self, message) -> None: ...
    def sendSystem(self, message) -> None: ...
    def stop_user_messages(self) -> None: ...
    def close(self) -> None: ...

